### ISSUE TITLE
Musiques qui se passent sans raisons

### ISSUE THREAD

**Issue by Dginos** [YKaeSse/SpotiBlindTest#1]
Les musiques se passent sans raisons. Bug à résoudre

**Comment by YKaeSse** [comment]
Some tracks do not have 30 second previews.
 preview_url : A link to a 30 second preview (MP3 format) of the track. null if not available.
 Certains track sont pas available du coup ca essayer de lancer une requete de preview 30 null.
 Je vais essayer de lancer que 30 sec de la musique mais pas sûr que j'arrive sinon je skiperai juste la musique sans la mettre dans l'historique
![Capture d'écran 2023-11-24 195748](https://github.com/YKaeSse/SpotiBlindTest/assets/21036180/2ab2c4a2-ae80-4251-ae86-164ae50cc8ee)

**Comment by YKaeSse** [comment]
Fichier concerné : src\app\blind-test\blind-test.component.ts
Fonction concerné : async nextMusic(firstLaunch: boolean = false) l.252
Correction du bug : 
Avant de lancer l'audio avec le preview, verification qu'il n'est pas null et fais un nextMusic().
![image](https://github.com/YKaeSse/SpotiBlindTest/assets/21036180/f6253720-9f41-4011-b251-2d9120c4e0be)
![image](https://github.com/YKaeSse/SpotiBlindTest/assets/21036180/6d5732e6-e1d4-4898-a239-0f910de10d86)
Pour eviter qu'il soit ajouté dans l'historique, verification supplementaire au debut de nextMusic()
![image](https://github.com/YKaeSse/SpotiBlindTest/assets/21036180/0ca4dcfd-1209-4da0-a8c5-4c6410a9d30f)

**Comment by YKaeSse** [comment]
Solution pour jouer le son au lieu de le skip : très compliqué et pas éthique 
https://developer.spotify.com/documentation/embeds
Spotify propose un 'embeded widget' pour tous les sons même ceux sans preview : qui est un lecteur interne.
Ca ressemble à ca :
![image](https://github.com/YKaeSse/SpotiBlindTest/assets/21036180/3e91346c-0ed0-4c60-8799-ca8433123cd7)

Tu recois une integreation HTML CSS pour avoir directement ca dans ton site.
Exemple : 
`html 
<iframe width=\"100%\" height=\"152\" title=\"Spotify Embed: My Path to Spotify: Women in Engineering \" style=\"border-radius: 12px\" frameborder=\"0\" allowfullscreen allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" src=\"https://open.spotify.com/embed/episode/7makk4oTQel546B0PZlDM5?utm_source=oembed\"></iframe>
`

J'ai pas regardé en détail mais je pense du coup qu'on peu extraire la source audio et mettre play et tt mais ca violerait les terms d'utilisation.
Donc autant skip les sons comme expliqué au dessus
